INSERT INTO products (id, name, size, description, price_cents, stock, featured, sku) VALUES
(1, 'Holiday Sweater Green','XXS',
 'Dress your furry friend in cozy, handmade style this holiday season! This charming dog sweater features a rich forest green body adorned with a delicate white snowflake Fair Isle pattern that wraps around the chest. The classic design is finished with a soft white ribbed collar and trim for a timeless winter look.',
 3050, 20, TRUE,  'HOL-GRN-XXS'),
(2, 'Holiday Sweater Green','XS',
 'Dress your furry friend in cozy, handmade style this holiday season!',
 2999, 50, FALSE, 'HOL-GRN-XS'),
(3, 'Holiday Sweater Green','SMALL',
 'Dress your furry friend in cozy, handmade style this holiday season!',
 3999, 75, FALSE, 'HOL-GRN-S'),
(4, 'Holiday Sweater Green','MEDIUM',
 'Dress your furry friend in cozy, handmade style this holiday season!',
 4999, 20, FALSE, 'HOL-GRN-M'),
(5, 'Holiday Sweater Red','XXS',
 'Dress your furry friend in cozy, handmade style this holiday season!',
 5999, 10, TRUE,  'HOL-RED-XXS'),
(6, 'Holiday Sweater Red','XS',
 'Description for Product F',
 6999, 5, FALSE,  'HOL-RED-XS'),
(7, 'Holiday Sweater Red','SMALL',
 'Description for Product G',
 7999, 15, FALSE, 'HOL-RED-S'),
(8, 'Holiday Sweater Red','MEDIUM',
 'Description for Product H',
 8999, 25, FALSE, 'HOL-RED-M');